id: P003133
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC452
  title: 'གསོ་བྱ་ལུས་ཀྱི་ཐ་སྙད་མཛོད། '
  author: ''
  volumes:
    8c4b32d26604450f848bd4648f463d72:
      image_group_id: I2PD17953
      title: ''
      volume_number: 1
      total_pages: 262
