id: IB46B42A0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:57:50+00:00'
last_modified: '2022-06-07T17:49:10.710169+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC452
  title: 'གསོ་བྱ་ལུས་ཀྱི་ཐ་སྙད་མཛོད། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '7289':
      image_group_id: I2PD17953
      title: ''
      total_pages: 262
      order: 1
      base_file: 7289.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
